/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dev.nizarfadlan.tugas3;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author nizar
 */
public class Tugas3 extends javax.swing.JFrame implements Runnable {

  /**
   * Creates new form Tugas3
   */
  public Tugas3() {
    initComponents();
    Thread t = new Thread(this);
    t.start();
    this.setTitle("Program Penjadwalan SMP");
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    labelClockAndDate = new javax.swing.JLabel();
    labelJam = new javax.swing.JLabel();
    labelDate = new javax.swing.JLabel();
    jMenuBar1 = new javax.swing.JMenuBar();
    menuGuru = new javax.swing.JMenu();
    menuManagementGuru = new javax.swing.JMenuItem();
    menuMapel = new javax.swing.JMenu();
    menuManagementMapel = new javax.swing.JMenuItem();
    menuTambahGuruMapel = new javax.swing.JMenuItem();
    menuJadwal = new javax.swing.JMenu();
    menuManagementJadwal = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setBackground(new java.awt.Color(204, 153, 255));
    setSize(new java.awt.Dimension(768, 1024));

    jPanel1.setBackground(new java.awt.Color(204, 153, 255));

    labelClockAndDate.setFont(new java.awt.Font("Source Code Pro Black", 0, 24)); // NOI18N
    labelClockAndDate.setText("TANGGAL DAN WAKTU");

    labelJam.setFont(new java.awt.Font("Source Code Pro Black", 0, 18)); // NOI18N
    labelJam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    labelJam.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    labelJam.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

    labelDate.setFont(new java.awt.Font("Source Code Pro Black", 0, 18)); // NOI18N
    labelDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    labelDate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    labelDate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(58, 58, 58)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(labelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(labelJam, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(57, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(labelClockAndDate)
        .addGap(80, 80, 80))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(107, 107, 107)
        .addComponent(labelClockAndDate)
        .addGap(18, 18, 18)
        .addComponent(labelJam, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(labelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(463, Short.MAX_VALUE))
    );

    menuGuru.setText("Guru");

    menuManagementGuru.setText("Management");
    menuManagementGuru.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuManagementGuruActionPerformed(evt);
      }
    });
    menuGuru.add(menuManagementGuru);

    jMenuBar1.add(menuGuru);

    menuMapel.setText("Mapel");

    menuManagementMapel.setText("Management");
    menuManagementMapel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuManagementMapelActionPerformed(evt);
      }
    });
    menuMapel.add(menuManagementMapel);

    menuTambahGuruMapel.setText("Tambah Guru");
    menuTambahGuruMapel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuTambahGuruMapelActionPerformed(evt);
      }
    });
    menuMapel.add(menuTambahGuruMapel);

    jMenuBar1.add(menuMapel);

    menuJadwal.setText("Jadwal");

    menuManagementJadwal.setText("Management");
    menuManagementJadwal.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuManagementJadwalActionPerformed(evt);
      }
    });
    menuJadwal.add(menuManagementJadwal);

    jMenuBar1.add(menuJadwal);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void menuManagementJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManagementJadwalActionPerformed
    InputJadwal jadwal = null;
    try {
      jadwal = new InputJadwal();
    } catch (ClassNotFoundException | SQLException ex) {
      Logger.getLogger(Tugas3.class.getName()).log(Level.SEVERE, null, ex);
    }
    jadwal.setVisible(true);
  }//GEN-LAST:event_menuManagementJadwalActionPerformed

  private void menuManagementGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManagementGuruActionPerformed
    InputGuru guru = null;
    try {
      guru = new InputGuru();
    } catch (ClassNotFoundException | SQLException ex) {
      Logger.getLogger(Tugas3.class.getName()).log(Level.SEVERE, null, ex);
    }
    guru.setVisible(true);
  }//GEN-LAST:event_menuManagementGuruActionPerformed

  private void menuManagementMapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManagementMapelActionPerformed
    InputMapel mapel = null;
    try {
      mapel = new InputMapel();
    } catch (ClassNotFoundException | SQLException ex) {
      Logger.getLogger(Tugas3.class.getName()).log(Level.SEVERE, null, ex);
    }
    mapel.setVisible(true);
  }//GEN-LAST:event_menuManagementMapelActionPerformed

  private void menuTambahGuruMapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTambahGuruMapelActionPerformed
    InputGuruMapel guruMapel = null;
    try {
      guruMapel = new InputGuruMapel();
    } catch (ClassNotFoundException | SQLException ex) {
      Logger.getLogger(Tugas3.class.getName()).log(Level.SEVERE, null, ex);
    }
    guruMapel.setVisible(true);
  }//GEN-LAST:event_menuTambahGuruMapelActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Tugas3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Tugas3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Tugas3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Tugas3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Tugas3().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JLabel labelClockAndDate;
  private javax.swing.JLabel labelDate;
  private javax.swing.JLabel labelJam;
  private javax.swing.JMenu menuGuru;
  private javax.swing.JMenu menuJadwal;
  private javax.swing.JMenuItem menuManagementGuru;
  private javax.swing.JMenuItem menuManagementJadwal;
  private javax.swing.JMenuItem menuManagementMapel;
  private javax.swing.JMenu menuMapel;
  private javax.swing.JMenuItem menuTambahGuruMapel;
  // End of variables declaration//GEN-END:variables

  @Override
  public void run() {
    while(true) {
      Calendar cal = Calendar.getInstance();
      
      SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm:ss");
      SimpleDateFormat dateFormat = new SimpleDateFormat("EEEE, dd/MM/yyyy");
      
      Date timeDate = cal.getTime();
      String time = timeFormat.format(timeDate);
      labelJam.setText(time);
      
      String date = dateFormat.format(timeDate);
      labelDate.setText(date);
    }
  }
}
